import Image from "next/image";
import { Inter } from "next/font/google";
import Head from "next/head";
import Login from "@/components/Auth/Login";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	return (
		<>
			<Head>
				<title>Capital Transaction | register</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="min-h-screen flex flex-col sm:flex-row overflow-y-auto"></main>
		</>
	);
}
